### ISSUE TITLE
Crashing when running app directly

### ISSUE THREAD

**Issue by VanHoevenTR** [Polarmods/PolarImGui#1]
This is all I get when running the app directly but it works fine in game. Can you make it work directly to test quickly?

```
2022-06-16 18:23:15.457 4128-4128/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.toshi.imguiandroid, PID: 4128
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.toshi.imguiandroid/com.toshi.imguiandroid.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.toshi.imguiandroid.MainActivity" on path: DexPathList[[zip file "/data/app/com.toshi.imguiandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.toshi.imguiandroid-1/lib/arm, /data/app/com.toshi.imguiandroid-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2568)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
```

**Comment by BryanGIG** [comment]
The project is design to only work when implemented into game, I think there will be no fix in this issue.

**Comment by BryanGIG** [comment]
> So no quick test then? really pain to recompile apk every changes

for designing purpose you can use [imgui_android_example](https://github.com/ocornut/imgui/tree/master/examples/example_android_opengl3), and then copy the ui into your project
